ci(deploy): adding flyctl actions

diff --git a/.github/workflows/deploy-api.yml b/.github/workflows/deploy-api.yml
--- a/.github/workflows/deploy-api.yml
+++ b/.github/workflows/deploy-api.yml
@@ -27,22 +27,20 @@ jobs:
       - name: Install dependencies
         run: |
           yarn install
-          
+
       - name: Build application
         run: |
-          yarn build
+          yarn run api:build
 
       - name: Prune development dependencies
         run: |
           npm prune --production
-
-      - name: Install Fly.io CLI
-        run: |
-          curl -L https://fly.io/install.sh | sh
-          echo 'export PATH="$HOME/.fly/bin:$PATH"' >> $GITHUB_ENV
+      
+      - name: Set up Flyctl
+        uses: superfly/flyctl-actions/setup-flyctl@master
 
       - name: Deploy to Fly.io
+        run: |
+          flyctl deploy --remote-only --config apps/api/fly.toml || { echo 'Deployment failed'; exit 1; }
         env:
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
-        run: |
-          fly deploy --remote-only --config apps/api/fly.toml || { echo 'Deployment failed'; exit 1; }
