fix(ci): adding fly app name

diff --git a/.github/workflows/deploy-api.yml b/.github/workflows/deploy-api.yml
--- a/.github/workflows/deploy-api.yml
+++ b/.github/workflows/deploy-api.yml
@@ -31,13 +31,13 @@ jobs:
       - name: Prune dependencies and prepare output
         run: |
           npx turbo prune --scope=api --docker && cd out && yarn install --frozen-lockfile && yarn run build
-          
+
       - name: Set up Flyctl
         uses: superfly/flyctl-actions/setup-flyctl@master
 
       - name: Deploy to Fly.io
         working-directory: out 
         run: |
-          flyctl deploy --remote-only --config ../fly.toml || { echo 'Deployment failed'; exit 1; }
+          flyctl deploy --remote-only --config ../fly.toml -a user-management-api || { echo 'Deployment failed'; exit 1; }
         env:
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
