ci(api): já nã osei

diff --git a/.github/workflows/deploy-api.yml b/.github/workflows/deploy-api.yml
--- a/.github/workflows/deploy-api.yml
+++ b/.github/workflows/deploy-api.yml
@@ -28,19 +28,16 @@ jobs:
         run: |
           yarn install
 
-      - name: Build application
+      - name: Prune dependencies and prepare output
         run: |
-          yarn run api:build
-
-      - name: Prune development dependencies
-        run: |
-          npm prune --production
-      
+          npx turbo prune --scope=api --docker && cd out && yarn install --frozen-lockfile && yarn run build
+          
       - name: Set up Flyctl
         uses: superfly/flyctl-actions/setup-flyctl@master
 
       - name: Deploy to Fly.io
+        working-directory: out 
         run: |
-          cd apps/api && flyctl deploy --remote-only --config apps/api/fly.toml || { echo 'Deployment failed'; exit 1; }
+          flyctl deploy --remote-only --config ../fly.toml || { echo 'Deployment failed'; exit 1; }
         env:
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
