fix(ci): combining steps

diff --git a/.github/workflows/deploy-api.yaml b/.github/workflows/deploy-api.yaml
--- a/.github/workflows/deploy-api.yaml
+++ b/.github/workflows/deploy-api.yaml
@@ -15,28 +15,28 @@ jobs:
   build:
     runs-on: ubuntu-latest
     env:
-      API_JWT_SECRET: ${{secrets.API_JWT_SECRET}}
+      API_JWT_SECRET: ${{ secrets.API_JWT_SECRET }}
       DB_DATABASE: ${{ secrets.DB_DATABASE }}
-      DB_HOST: ${{secrets.DB_HOST}}
-      DB_PORT: ${{secrets.DB_PORT}}
-      DB_USERNAME: ${{secrets.DB_USERNAME}}
-      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
+      DB_HOST: ${{ secrets.DB_HOST }}
+      DB_PORT: ${{ secrets.DB_PORT }}
+      DB_USERNAME: ${{ secrets.DB_USERNAME }}
+      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
 
     strategy:
       matrix:
         node-version: [18.x]
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
 
       - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
 
       - name: Get yarn cache directory path
         id: yarn-cache-dir-path
-        run: echo "::set-output name=dir::$(yarn cache dir)"
+        run: echo "dir=$(yarn cache dir)" >> $GITHUB_ENV
 
       - name: Cache node modules
         uses: actions/cache@v2
@@ -44,14 +44,10 @@ jobs:
           cache-name: cache-node-modules
         id: yarn-cache
         with:
-          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          path: ${{ env.dir }}
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-yarn-
-
-      - run: yarn global add turbo
-      - run: npx nps build.ci.api
-      - run: npx nps test.ci.api
 
   deploy:
     runs-on: ubuntu-latest
@@ -59,7 +55,7 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Install Vercel CLI
         run: npm install -g vercel
@@ -74,6 +70,8 @@ jobs:
           DB_USERNAME: ${{ secrets.DB_USERNAME }}
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         run: |
+          yarn global add turbo
           npx nps prepare.ci.api
-          cd out
-          vercel --name user-management-api --prod --yes --token=$VERCEL_TOKEN --env API_JWT_SECRET=$API_JWT_SECRET --env DB_DATABASE=$DB_DATABASE --env DB_HOST=$DB_HOST --env DB_PORT=$DB_PORT --env DB_USERNAME=$DB_USERNAME --env DB_PASSWORD=$DB_PASSWORD
+          npx nps build.ci.api
+          npx nps test.ci.api || { echo 'Tests failed'; exit 1; }
+          cd out && vercel --name user-management-api --prod --confirm --token=$VERCEL_TOKEN --env API_JWT_SECRET=$API_JWT_SECRET --env DB_DATABASE=$DB_DATABASE --env DB_HOST=$DB_HOST --env DB_PORT=$DB_PORT --env DB_USERNAME=$DB_USERNAME --env DB_PASSWORD=$DB_PASSWORD || { echo 'Deployment failed'; exit 1; }
